# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-11 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publish',
        ),
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.ManyToManyField(db_constraint=False, to='appo.Publish'),
        ),
    ]
